language:          python

python:
  - 3.6.7

branches:
  - master

install:
  - pip install -r requirements.txt

script:
  - null

before_deploy:
  - mkdocs build --verbose --clean --strict

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master


after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

notifications:
  email:           false
