# Project Information
site_name: Minenamia Law
site_description: All Content is provided by the Department of Law(DOL). Any unethical, immoral laws, please report to HR DOL’s immediately.
site_url: https://www.minenamia-law.tk

# Copyright
copyright: 'Copyright &copy; 2018 Mattcre And Richie Bendall'

# Configuration
theme:
  name: 'bootstrap386'

# Page Tree
pages:
    - Law: index.md
    - Weapon Classes: weapon-classes.md

extra_css:
  - css/details-support.css

extra_javascript:
  - js/details-support.js

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - smarty
  - admonition
